dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide1819 password 'decide1819'"
  - psql -U postgres -c "create database test_decide1819 owner decide1819"
  - psql -U postgres -c "ALTER USER decide1819 CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test mixnet --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml
branches:
  if: branch = master
